#!/bin/bash

DATE=$(date +%Y%m%dT%H%M%S)
MANIPULATIONS=5
TRIALS=3
LOGDIR=run-$DATE
KEYPAIR=Mesos
KEYPAIRFILE=/work/ankurd/keys/Mesos.pem
AWSKEYFILE=/work/ankurd/keys/env.sh
INSTANCETYPE=m1.large
ZONE=us-east-1d
CLUSTERNAME=KMeans

mkdir -p $LOGDIR

source $AWSKEYFILE

echo "Starting experiment"
for manip in $(seq 0 $(expr $MANIPULATIONS - 1))
do
  let NUMSLAVES=2 ** $manip
  echo "Number of slaves: $NUMSLAVES"
  
  echo "Launching cluster..."
  mesos-ec2 --slaves=$NUMSLAVES --key-pair=$KEYPAIR --identity-file=$KEYPAIRFILE --instance-type=$INSTANCETYPE --zone=$ZONE launch $CLUSTERNAME

  MASTER=$(mesos-ec2 -k $KEYPAIR -i $KEYPAIRFILE get-master $CLUSTERNAME | tail -n 1)
  MESOSMASTER=$(curl http://$MASTER:8080 2>/dev/null | perl -ne 'print $1 if /^PID: (.*)<br \/>/')
  echo "Master public hostname: $MASTER"
  echo "Master Mesos PID: $MESOSMASTER"

  echo "Generating point file..."
  ssh -i $KEYPAIRFILE root@$MASTER 'source ~/.profile; cd kmeans-spark; ./run KMeansDataGenerator 3 10000000 1 > pts.dat; ../hadoop-0.20.2/bin/hadoop fs -put pts.dat /'
  export POINTFILE=hdfs://$MASTER:9000/pts.dat

  echo "Starting performance run..."
  for trial in $(seq 1 $TRIALS)
  do
    echo "Trial $trial"
    ssh -i $KEYPAIRFILE root@$MASTER "source ~/.profile; cd kmeans-spark; ./run SparkKMeans $POINTFILE 3 $MESOSMASTER 7,40 45,35 20,8" 2>&1 | tee $LOGDIR/$manip-$trial.log
  done
done
