#!/bin/bash

source common-options.sh

MAXINSTANCETYPEINDEX=3
INSTANCETYPES[0]='m1.large'
INSTANCETYPES[1]='m1.xlarge'
INSTANCETYPES[2]='m2.xlarge'
INSTANCETYPES[3]='c1.xlarge'
MEMORYS[0]='6500m'
MEMORYS[1]='14g'
MEMORYS[2]='16g'
MEMORYS[3]='6g'
LOGDIR=run-scaleup-$DATE
NUMPOINTS=100000000
NUMSLAVES=2

echo "Starting experiment..."
for manip in $(seq 0 $MAXINSTANCETYPEINDEX)
do
  INSTANCETYPE=${INSTANCETYPES[$manip]}
  MEMORY=${MEMORYS[$manip]}
  echo "Using instance type $INSTANCETYPE with $MEMORY memory"

  source init-cluster.sh
  
  echo "Starting performance run..."
  for trial in $(seq 1 $TRIALS)
  do
    echo "Trial $trial..."
    ssh -i $KEYPAIRFILE root@$MASTER \
	"source ~/.profile; \
	cd kmeans-spark; \
	./run SparkKMeans $POINTFILE 3 $MESOSMASTER 7,40 45,35 20,8" \
	2>&1 | tee $LOGDIR/$manip-$trial.log 2>&1 | sed 's/^/    /'
  done

  echo "Ending performance run..."
  echo y | mesos-ec2 --key-pair=$KEYPAIR --identity-file=$KEYPAIRFILE destroy $CLUSTERNAME
done
