#!/bin/bash

source common-options.sh

MANIPULATIONS=5
LOGDIR=run-scaleout-$DATE
INSTANCETYPE=m1.large
MEMORY=6500m
NUMPOINTS=100000000

echo "Starting experiment..."
for manip in $(seq 1 $MANIPULATIONS)
do
  let NUMSLAVES=2**$manip
  echo "Number of slaves: $NUMSLAVES"
  
  source init-cluster.sh
  
  echo "Starting performance run..."
  for trial in $(seq 1 $TRIALS)
  do
    echo "Trial $trial..."
    ssh -i $KEYPAIRFILE root@$MASTER \
	"source ~/.profile; \
	cd kmeans-spark; \
	./run SparkKMeans $POINTFILE 3 $MESOSMASTER 7,40 45,35 20,8" \
	2>&1 | tee $LOGDIR/$manip-$trial.log
  done

  echo "Ending performance run..."
  echo y | mesos-ec2 --key-pair=$KEYPAIR --identity-file=$KEYPAIRFILE destroy $CLUSTERNAME
done
